name: Compilation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # On va construire différentes versions en parallèle
    strategy:
      matrix:
        version:
          - 290
          - 291
          - 292
          - 293
          - 294
          - 354

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Installation de l’outil arduino-cli
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      # Récup index outils expressifs
      - name: Update index
        run: arduino-cli core update-index --additional-urls https://dl.espressif.com/dl/package_esp32_index.json
      # Install outils expressifs
      - name: Install core
        run: arduino-cli core install esp32:esp32 --additional-urls https://dl.espressif.com/dl/package_esp32_index.json
      # Partie à revoir. Pour le moment, je recopie les librairies depuis le dépôt vers le répertoire Arduino
      - name: install libs
        run: |
          mkdir /home/runner/Arduino
          cp -r "${GITHUB_WORKSPACE}/Sources/Beta Code/Ide Arduino/libraries/" /home/runner/Arduino
      # Supprimé. À la place, j’ai mis un #ifndef dans le .h. Comme ça, rien ne change pour les autres usages, mais on peut forcer la valeur ici avec -D
      # - name: patch src
      #  run: sed -i -e s'|^#define VARIOVERSION|//#define VARIOVERSION|g' "${GITHUB_WORKSPACE}/Sources/Beta Code/Ide Arduino/libraries/HardwareConfig/HardwareConfig.h"
      # Compilation, en utilisant -D pour paramétrer les versions.
      - name: compile ${{ matrix.version }}
        run: |
          arduino-cli compile -v \
          -b esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=min_spiffs,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,DebugLevel=none \
          --build-property "build.extra_flags=-DVARIOVERSION=${{ matrix.version }} -DESP32" \
          --output-dir arduino_build_${{ matrix.version }} \
          "${GITHUB_WORKSPACE}/Sources/Beta Code/Ide Arduino/Gnuvario-E/Gnuvario-E"
      # Récup des fichiers compilés
      - name: Upload bin file ${{ matrix.version }}
        uses: actions/upload-artifact@v2.2.3
        with:
            name: Gnuvario-E-${{ matrix.version }}.bin
            path: "arduino_build_${{ matrix.version }}/Gnuvario-E.ino.bin"
            retention-days: 1
      - name: Upload partition file ${{ matrix.version }}
        uses: actions/upload-artifact@v2.2.3
        with:
            name: Gnuvario-E-${{ matrix.version }}.partitions.bin
            path: "arduino_build_${{ matrix.version }}/Gnuvario-E.ino.partitions.bin"
            retention-days: 1
