# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Update index
        run: arduino-cli core update-index --additional-urls https://dl.espressif.com/dl/package_esp32_index.json
      - name: Install core
        run: arduino-cli core install esp32:esp32 --additional-urls https://dl.espressif.com/dl/package_esp32_index.json
      - name: install libs
        run: |
          mkdir Arduino
          cp -r "Sources/Beta Code/Ide Arduino/libraries/" Arduino/
      - name: patch src
        run: sed -i -e s'|^#define VARIOVERSION|//#define VARIOVERSION|g' "Sources/Beta Code/Ide Arduino/libraries/HardwareConfig/HardwareConfig.h"
      - name: compile
        run: |
          arduino-cli compile -v --clean -e \
          -b esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=min_spiffs,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,DebugLevel=none \
          --build-property "build.extra_flags=-DVARIOVERSION=291" \
          --output-dir arduino_build \
          "Sources/Beta Code/Ide Arduino/Gnuvario-E/Gnuvario-E"

